// Real browser input + read-only, source-backed evidence frames. No game source mutations.
import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import assert from 'node:assert/strict';
const root=process.cwd(),raw=path.join(root,'artifacts/capstone/raw');
await fs.mkdir(raw,{recursive:true});
const read=p=>fs.readFile(path.join(root,p),'utf8');
const git=(...args)=>execFileSync('git',['-c',`safe.directory=${root.replaceAll('\\','/')}`,...args],{encoding:'utf8'});
const manifest=JSON.parse(await read('artifacts/capstone/raw/narration-manifest.json'));
const intro=manifest.segments[0].duration+.2,play=manifest.segments[1].duration+.2;
const browser=await chromium.launch();
if(!process.env.CAPSTONE_FRAMES_ONLY){
const context=await browser.newContext({viewport:{width:1920,height:1080},recordVideo:{dir:raw,size:{width:1920,height:1080}}});
const opened=Date.now(),page=await context.newPage(),errors=[],events=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.CAPSTONE_DEMO_URL||'http://127.0.0.1:4180/');
await page.waitForFunction(()=>!!window.__FRUIT_MERGE_TEST__);
await page.evaluate(()=>document.body.style.zoom='1.15');
// Deliberately prepared scene. All subsequent drops/merges/pause/restart use real mouse input.
await page.evaluate(()=>window.__FRUIT_MERGE_TEST__.load([{rank:20,x:110,y:610},{rank:18,x:365,y:620},{rank:1,x:240,y:650}],1));
await page.waitForTimeout(2200);
const started=Date.now();
const until=async sec=>{const left=sec*1000-(Date.now()-started);if(left>0)await page.waitForTimeout(left);};
const snap=()=>page.evaluate(()=>window.__FRUIT_MERGE_TEST__.snapshot());
const mark=async name=>events.push({name,seconds:(Date.now()-started)/1000,snapshot:await snap()});
const drop=async x=>{const box=await page.locator('canvas').boundingBox();await page.mouse.move(box.x+box.width*x/480,box.y+box.height*.3,{steps:20});await page.mouse.click(box.x+box.width*x/480,box.y+box.height*.3);};
await mark('prepared scene');
await page.screenshot({path:path.join(raw,'game-intro.png')});
await until(intro+4.8);await drop(240);await mark('real pointer drop');
await page.waitForFunction(()=>window.__FRUIT_MERGE_TEST__.snapshot().state.score===10,{},{timeout:6000});
await mark('physical merge score10');
assert.deepEqual((await snap()).fruits.map(f=>f.rank).sort((a,b)=>a-b),[2,18,20]);
await page.screenshot({path:path.join(raw,'game-merge.png')});
await until(intro+11.8);await drop(290);
await until(intro+12.6);await page.getByRole('button',{name:'Пауза',exact:true}).click();
const paused=await snap();await mark('pause');
await until(intro+14.7);assert.deepEqual((await snap()).fruits,paused.fruits);
await page.getByRole('button',{name:'Продовжити',exact:true}).click();await mark('resume');
await until(intro+18);const bestBeforeRestart=(await snap()).state.bestScore;await page.getByRole('button',{name:'Нова гра',exact:true}).click();
const restarted=await snap();assert.equal(restarted.state.score,0);assert.equal(restarted.state.bestScore,bestBeforeRestart);assert.equal(restarted.fruits.length,0);await mark('restart preserves actual best');
await until(intro+22);await drop(240);
await until(intro+24);await drop(120);
await until(intro+play+.6);
const video=page.video();await context.close();
await fs.copyFile(await video.path(),path.join(raw,'gameplay.webm'));
await fs.writeFile(path.join(raw,'recording.json'),JSON.stringify({recordedAt:new Date().toISOString(),revision:git('rev-parse','HEAD').trim(),productTree:git('rev-parse','HEAD:src').trim(),gameplayTrimStart:(started-opened)/1000,introSeconds:intro,gameplaySeconds:play,events,errors,preparedScene:true,realInput:true},null,2));
assert.deepEqual(errors,[]);
}

const frames=await browser.newPage({viewport:{width:1920,height:1080}});
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const panel=(name,content)=>`<article><div class="file">${esc(name)}</div><pre>${esc(content)}</pre></article>`;
const base=(badge,title,sub,body)=>`<!doctype html><html lang="uk"><meta charset="utf-8"><style>*{box-sizing:border-box}body{margin:0;background:#101e21;color:#f7f1df;font:30px 'Segoe UI',sans-serif;padding:66px 90px}header{color:#d9b764;font-size:23px;letter-spacing:3px}h1{font-size:54px;margin:17px 0 12px}p{font-size:27px;color:#bfd1c9;margin:0 0 30px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:26px}article{background:#192e31;border:1px solid #466264;border-radius:20px;overflow:hidden}.file{background:#254044;padding:17px 23px;font-size:22px;color:#efd89a}pre{white-space:pre-wrap;overflow-wrap:anywhere;margin:0;padding:25px;font:27px/1.48 Consolas,'Segoe UI',monospace}footer{position:absolute;bottom:155px;font-size:20px;color:#a8bdb6}.wide{grid-column:1/-1}strong{color:#e8ca79}</style><header>${badge}</header><h1>${title}</h1><p>${sub}</p>${body}<footer>Fruit Merge Capstone · реальні джерела проєкту · 04.10.2026</footer></html>`;
const save=async(id,html)=>{await fs.writeFile(path.join(raw,`${id}.html`),html);await frames.setContent(html);await frames.screenshot({path:path.join(raw,`${id}.png`)});assert.equal(await frames.evaluate(()=>document.documentElement.scrollHeight),1080);};
const agents=await read('AGENTS.md'),coord=await read('src/game/services/merge-coordinator.ts');
const rule=agents.split('\n').find(s=>s.includes('Захищай обидва ID'));
const code=coord.split('\n').find(s=>s.includes("a.status=b.status='merging'")).trim().replaceAll(';this.queue',';\nthis.queue').replaceAll(';return',';\nreturn');
const history=git('log','--reverse','--format=%h %s','--','AGENTS.md','src/game/domain/merge.ts').trim().split('\n').slice(0,2).join('\n');
await save('context',base('01 / КОНТЕКСТ + SDD','Правило → код → перевірка','Документація передувала реалізації. Нижче — точні фрагменти файлів.',`<div class="grid">${panel('AGENTS.md · обов’язкове правило',rule)}${panel('src/game/services/merge-coordinator.ts · фрагмент',code)}<div class="wide">${panel('git log --reverse · AGENTS.md / merge.ts',history)}</div></div>`));
const red=(await read('docs/evidence/runs/review-physics-red.log')).split('\n').filter(s=>/Error: expect|Expected:|Received:|  1 failed/.test(s)).join('\n');
const diff=git('show','e77427a','--','src/game/physics/matter-adapter.ts');
await fs.writeFile(path.join(raw,'historical-fix.diff'),diff);
const before=diff.split('\n').find(s=>s.startsWith('- const image='));
const after=diff.split('\n').find(s=>s.startsWith('+ const image='));
const focus=line=>line.match(/\.set(?:Circle|DisplaySize).*?\.setBounce/)[0].replace('.setBounce','').replace(').',')\n.');
const green=(await read('docs/evidence/runs/final-check.log')).split('\n').filter(s=>/24 passed|CHECK PASSED/.test(s)).join('\n');
await save('verification',base('02 / ВЕРИФІКАЦІЯ + ЦИКЛ АГЕНТА','Знайшли → відтворили → виправили','Історичні докази · фрагменти збережених прогонів, не live-термінал.',`<div class="grid">${panel('review-physics-red.log · f224a78 · exit 1',red)}${panel('git diff e77427a · точні ланцюжки викликів','ДО\n'+focus(before)+'\n\nПІСЛЯ\n'+focus(after))}<div class="wide">${panel('final-check.log · після e77427a · exit 0',green)}</div></div>`));
const review=await read('docs/reviews/capstone-review.md');
const verdict=review.split('\n').find(s=>s.startsWith('**Approve')).replaceAll('**','');
const check=(await read('docs/evidence/runs/capstone-final-check.log')).replace(/\x1b\[[0-9;]*m/g,'').split('\n').filter(s=>/Tests\s+76 passed|Tests\s+7 passed|33 passed|CHECK PASSED/.test(s)).join('\n');
const meta=JSON.parse(await read('docs/evidence/runs/capstone-final-check.json'));
await save('review',base('03 / MAKER ≠ CHECKER','Окремий reviewer. Свіжий повний check.','Рев’ю та авторський прогін — окремі перевірки з різними межами.',`<div class="grid">${panel('docs/reviews/capstone-review.md · фрагмент',verdict+'\n\n'+review.split('\n').filter(s=>s.startsWith('- Pause snapshot')||s.startsWith('- 10 restart')).join('\n'))}${panel('capstone-final-check.log / .json · 04.10.2026',check+'\n\nrevision: '+meta.revision.slice(0,12)+'\nexitCode: '+meta.exitCode+'\nРобоче дерево перед check: чисте')}</div>`));
await save('outro',base('04 / ЛЮДИНА + АГЕНТ','Рішення людини. Перевірювана робота агента.','Джерело: docs/submission/human-agent-roles.md · стислий виклад',`<div class="grid">${panel('Підтверджені рішення учасника','Концепт фруктової гри\nКаталог із 30 фруктів\nВізуальні референси\nЗберегти поточну посудину\nГеометрична прогресія розмірів')}${panel('Фактично виконав агент','Код і автоматичні тести\nАналіз невдач і виправлення\nНезалежні reviewer-сесії\nПублікація гри\nУкраїнське відео та докази')}<div class="wide">${panel('Грати без встановлення · матеріали в репозиторії','dmitryyr.github.io/fruit-merge-capstone/\ngithub.com/DmitryyR/fruit-merge-capstone')}</div></div>`));
await browser.close();console.log('Recorded real input, first physical merge=10, pause/resume, restart preserves actual best; 4 source frames.');
