import {test,expect,type Page} from '@playwright/test';
type Seed={rank:number;x:number;y:number;static?:boolean};
async function ready(page:Page){await page.goto('/');await expect(page.locator('canvas')).toBeVisible();await page.waitForFunction(()=>!!window.__FRUIT_MERGE_TEST__);}
async function seed(page:Page,fruits:Seed[]=[],currentRank=1){await page.evaluate(({fruits,currentRank})=>window.__FRUIT_MERGE_TEST__!.load(fruits,currentRank),{fruits,currentRank});}
async function snap(page:Page){return page.evaluate(()=>window.__FRUIT_MERGE_TEST__!.snapshot());}
async function drop(page:Page,touch:boolean,x=240){const r=await page.locator('canvas').boundingBox();if(!r)throw new Error('canvas missing');const px=r.x+r.width*x/480,py=r.y+r.height*0.4;if(touch)await page.touchscreen.tap(px,py);else await page.mouse.click(px,py);}
test('FR-01 ready with all 30 textures',async({page})=>{await ready(page);expect((await snap(page)).textures).toBe(30);await expect(page.getByRole('heading',{name:'Фруктовий сад',exact:true})).toBeVisible();});
test('FR-02/03 real drop and collision award score',async({page,isMobile})=>{await ready(page);await seed(page,[{rank:1,x:240,y:650}]);await drop(page,isMobile);await expect.poll(async()=>(await snap(page)).state.score).toBe(10);expect((await snap(page)).fruits.map(f=>f.rank)).toEqual([2]);});
test('FR-05 cooldown blocks same-frame gestures without shifting queue',async({page})=>{await ready(page);await seed(page);const result=await page.evaluate(()=>{const canvas=document.querySelector('canvas')!;const r=canvas.getBoundingClientRect();const gesture=(id:number,x:number)=>{const data={pointerId:id,isPrimary:true,clientX:r.x+r.width*x/480,clientY:r.y+r.height*.4,bubbles:true};canvas.dispatchEvent(new PointerEvent('pointerdown',data));canvas.dispatchEvent(new PointerEvent('pointerup',data));};gesture(1,50);const first=window.__FRUIT_MERGE_TEST__!.snapshot();gesture(2,400);return {first,second:window.__FRUIT_MERGE_TEST__!.snapshot()};});expect(result.second.fruits.length).toBe(1);expect(result.second.state.currentRank).toBe(result.first.state.currentRank);});
test('FR-07 pause freezes physics and timer; resume works',async({page,isMobile})=>{await ready(page);await seed(page);await drop(page,isMobile);await page.getByRole('button',{name:'Пауза',exact:true}).click();const a=await snap(page);await page.waitForTimeout(400);const b=await snap(page);expect(b.fruits).toEqual(a.fruits);expect(b.simTime).toBe(a.simTime);await drop(page,isMobile);expect((await snap(page)).fruits.length).toBe(1);await page.getByRole('button',{name:'Продовжити',exact:true}).click();await expect.poll(async()=>(await snap(page)).simTime).toBeGreaterThan(a.simTime);});
test('FR-06 danger ends session, restart unlocks it',async({page,isMobile})=>{await ready(page);await seed(page,[{rank:1,x:240,y:120,static:true}]);await expect.poll(async()=>(await snap(page)).state.mode,{timeout:8000}).toBe('gameOver');await drop(page,isMobile);expect((await snap(page)).fruits.length).toBe(1);await page.getByRole('button',{name:'Нова гра',exact:true}).click();expect((await snap(page)).state.mode).toBe('playing');expect((await snap(page)).fruits).toHaveLength(0);});
test('FR-08 record survives restart and reload',async({page,isMobile})=>{await ready(page);await seed(page,[{rank:1,x:240,y:650}]);await drop(page,isMobile);await expect.poll(async()=>(await snap(page)).state.bestScore).toBe(10);await page.getByRole('button',{name:'Нова гра',exact:true}).click();expect((await snap(page)).state.bestScore).toBe(10);await page.reload();await page.waitForFunction(()=>!!window.__FRUIT_MERGE_TEST__);expect((await snap(page)).state.bestScore).toBe(10);});
test('NFR-03 ten restarts keep one collision listener and one drop',async({page,isMobile})=>{await ready(page);for(let i=0;i<10;i++)await page.getByRole('button',{name:'Нова гра',exact:true}).click();await drop(page,isMobile);const s=await snap(page);expect(s.fruits).toHaveLength(1);expect(s.collisionListeners).toBe(1);});
test('NFR-02 resize uses new canvas geometry',async({page,isMobile})=>{await ready(page);await page.setViewportSize({width:600,height:900});await seed(page);await drop(page,isMobile,100);expect((await snap(page)).fruits[0].x).toBeCloseTo(100,0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);});
test('NFR-07 hidden tab automatically pauses',async({page})=>{await ready(page);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});expect((await snap(page)).state.mode).toBe('paused');});
test('outside release and secondary pointer do not drop',async({page})=>{await ready(page);await seed(page);const canvas=page.locator('canvas');await canvas.dispatchEvent('pointerdown',{pointerId:20,isPrimary:false});await canvas.dispatchEvent('pointerup',{pointerId:20,isPrimary:false,clientX:200,clientY:200});expect((await snap(page)).fruits).toHaveLength(0);await canvas.dispatchEvent('pointerdown',{pointerId:21,isPrimary:true});await page.evaluate(()=>window.dispatchEvent(new PointerEvent('pointerup',{pointerId:21,isPrimary:true,clientX:-50,clientY:-50})));expect((await snap(page)).fruits).toHaveLength(0);});

test('physics bodies preserve catalog diameter at every rank',async({page})=>{await ready(page);for(let rank=1;rank<=30;rank++){await seed(page,[{rank,x:240,y:400,static:true}]);const body=(await snap(page)).fruits[0];const diameter=24+3*(rank-1);expect(body.collisionWidth).toBeGreaterThan(diameter*.94);expect(body.collisionWidth).toBeLessThanOrEqual(diameter*1.01);}});
